-- ============================================================
-- dbt_finance 生产环境定时调度
-- 通过 Snowflake TASK 实现每日自动运行 dbt 项目
-- ============================================================

-- 方式一：如果已通过 CREATE DBT PROJECT 部署，使用 EXECUTE DBT PROJECT
CREATE OR REPLACE TASK TEST_SNOWFLAKE_LEANING.SCHM_F_SNOWLEARN_01.TASK_DBT_FINANCE_DAILY_RUN
  WAREHOUSE = COMPUTE_WH
  SCHEDULE = 'USING CRON 0 6 * * * Asia/Shanghai'
  COMMENT = 'Daily dbt_finance production run at 6:00 AM CST'
AS
  EXECUTE DBT PROJECT TEST_SNOWFLAKE_LEANING.SCHM_F_SNOWLEARN_01.DBT_FINANCE ARGS = 'run';

-- 测试任务（可选，在 run 完成后自动触发）
CREATE OR REPLACE TASK TEST_SNOWFLAKE_LEANING.SCHM_F_SNOWLEARN_01.TASK_DBT_FINANCE_DAILY_TEST
  WAREHOUSE = COMPUTE_WH
  COMMENT = 'Daily dbt_finance test after run'
  AFTER TEST_SNOWFLAKE_LEANING.SCHM_F_SNOWLEARN_01.TASK_DBT_FINANCE_DAILY_RUN
AS
  EXECUTE DBT PROJECT TEST_SNOWFLAKE_LEANING.SCHM_F_SNOWLEARN_01.DBT_FINANCE ARGS = 'test';

-- 启用任务（取消注释后执行）
-- ALTER TASK TEST_SNOWFLAKE_LEANING.SCHM_F_SNOWLEARN_01.TASK_DBT_FINANCE_DAILY_TEST RESUME;
-- ALTER TASK TEST_SNOWFLAKE_LEANING.SCHM_F_SNOWLEARN_01.TASK_DBT_FINANCE_DAILY_RUN RESUME;
